<?php

namespace Database\Seeders;

use App\Models\Quote;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuoteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $quotes = [
            // Wisdom
            ['text' => 'The only true wisdom is in knowing you know nothing.', 'author' => 'Socrates', 'category' => 'Wisdom'],
            ['text' => 'Knowledge speaks, but wisdom listens.', 'author' => 'Jimi Hendrix', 'category' => 'Wisdom'],
            ['text' => 'The fool doth think he is wise, but the wise man knows himself to be a fool.', 'author' => 'William Shakespeare', 'category' => 'Wisdom'],
            ['text' => 'Turn your wounds into wisdom.', 'author' => 'Oprah Winfrey', 'category' => 'Wisdom'],
            ['text' => 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', 'author' => 'Aristotle', 'category' => 'Wisdom'],
            ['text' => 'Do not seek to follow in the footsteps of the wise; seek what they sought.', 'author' => 'Matsuo Bashō', 'category' => 'Wisdom'],
            ['text' => 'The invariable mark of wisdom is to see the miraculous in the common.', 'author' => 'Ralph Waldo Emerson', 'category' => 'Wisdom'],
            ['text' => 'We are made wise not by the recollection of our past, but by the responsibility for our future.', 'author' => 'George Bernard Shaw', 'category' => 'Wisdom'],
            ['text' => 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'author' => 'Rumi', 'category' => 'Wisdom'],
            ['text' => 'A wise man speaks because he has something to say; a fool because he has to say something.', 'author' => 'Plato', 'category' => 'Wisdom'],
            ['text' => 'Honesty is the first chapter in the book of wisdom.', 'author' => 'Thomas Jefferson', 'category' => 'Wisdom'],
            ['text' => 'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'author' => 'Albert Einstein', 'category' => 'Wisdom'],
            ['text' => 'Silence is the sleep that nourishes wisdom.', 'author' => 'Francis Bacon', 'category' => 'Wisdom'],
            ['text' => 'The older I grow, the more I distrust the familiar doctrine that age brings wisdom.', 'author' => 'H.L. Mencken', 'category' => 'Wisdom'],
            ['text' => 'Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.', 'author' => 'Lao Tzu', 'category' => 'Wisdom'],
            ['text' => 'Common sense in an uncommon degree is what the world calls wisdom.', 'author' => 'Samuel Taylor Coleridge', 'category' => 'Wisdom'],
            ['text' => 'Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.', 'author' => 'Sandra Carey', 'category' => 'Wisdom'],
            ['text' => 'A man begins cutting his wisdom teeth the first time he bites off more than he can chew.', 'author' => 'Herb Caen', 'category' => 'Wisdom'],
            ['text' => 'The art of being wise is the art of knowing what to overlook.', 'author' => 'William James', 'category' => 'Wisdom'],
            ['text' => 'Wisdom is the reward you get for a lifetime of listening when you\'d have preferred to talk.', 'author' => 'Doug Larson', 'category' => 'Wisdom'],
            ['text' => 'Patience is the companion of wisdom.', 'author' => 'Saint Augustine', 'category' => 'Wisdom'],
            ['text' => 'By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', 'author' => 'Confucius', 'category' => 'Wisdom'],
            ['text' => 'It is unwise to be too sure of one\'s own wisdom. It is healthy to be reminded that the strongest might weaken and the wisest might err.', 'author' => 'Mahatma Gandhi', 'category' => 'Wisdom'],
            ['text' => 'Wisdom is knowing what to do next; virtue is doing it.', 'author' => 'David Starr Jordan', 'category' => 'Wisdom'],
            ['text' => 'Wonder is the beginning of wisdom.', 'author' => 'Socrates', 'category' => 'Wisdom'],
            ['text' => 'A fool is known by his speech; and a wise man by silence.', 'author' => 'Pythagoras', 'category' => 'Wisdom'],
            ['text' => 'The wisdom of the wise and the experience of the ages are perpetuated by quotations.', 'author' => 'Benjamin Disraeli', 'category' => 'Wisdom'],
            ['text' => 'Wisdom is like a baobab tree; no one individual can embrace it.', 'author' => 'African Proverb', 'category' => 'Wisdom'],
            ['text' => 'To acquire knowledge, one must study; but to acquire wisdom, one must observe.', 'author' => 'Marilyn vos Savant', 'category' => 'Wisdom'],
            ['text' => 'The doorstep to the temple of wisdom is a knowledge of our own ignorance.', 'author' => 'Benjamin Franklin', 'category' => 'Wisdom'],

            // Life
            ['text' => 'Life is what happens when you\'re busy making other plans.', 'author' => 'John Lennon', 'category' => 'Life'],
            ['text' => 'In the end, it\'s not the years in your life that count. It\'s the life in your years.', 'author' => 'Abraham Lincoln', 'category' => 'Life'],
            ['text' => 'The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.', 'author' => 'Ralph Waldo Emerson', 'category' => 'Life'],
            ['text' => 'Life is really simple, but we insist on making it complicated.', 'author' => 'Confucius', 'category' => 'Life'],
            ['text' => 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'author' => 'Buddha', 'category' => 'Life'],
            ['text' => 'Life isn\'t about finding yourself. Life is about creating yourself.', 'author' => 'George Bernard Shaw', 'category' => 'Life'],
            ['text' => 'The biggest adventure you can take is to live the life of your dreams.', 'author' => 'Oprah Winfrey', 'category' => 'Life'],
            ['text' => 'We are here to laugh at the odds and live our lives so well that Death will tremble to take us.', 'author' => 'Charles Bukowski', 'category' => 'Life'],
            ['text' => 'To live is the rarest thing in the world. Most people exist, that is all.', 'author' => 'Oscar Wilde', 'category' => 'Life'],
            ['text' => 'The most important thing is to enjoy your life—to be happy—it\'s all that matters.', 'author' => 'Audrey Hepburn', 'category' => 'Life'],
            ['text' => 'Life is a succession of lessons which must be lived to be understood.', 'author' => 'Helen Keller', 'category' => 'Life'],
            ['text' => 'You only live once, but if you do it right, once is enough.', 'author' => 'Mae West', 'category' => 'Life'],
            ['text' => 'The unexamined life is not worth living.', 'author' => 'Socrates', 'category' => 'Life'],
            ['text' => 'Life is 10% what happens to us and 90% how we react to it.', 'author' => 'Charles R. Swindoll', 'category' => 'Life'],
            ['text' => 'Change is the law of life. And those who look only to the past or present are certain to miss the future.', 'author' => 'John F. Kennedy', 'category' => 'Life'],
            ['text' => 'Difficulties in life are intended to make us better, not bitter.', 'author' => 'Dan Reeves', 'category' => 'Life'],
            ['text' => 'We must be willing to let go of the life we planned so as to have the life that is waiting for us.', 'author' => 'Joseph Campbell', 'category' => 'Life'],
            ['text' => 'The good life is one inspired by love and guided by knowledge.', 'author' => 'Bertrand Russell', 'category' => 'Life'],
            ['text' => 'Life is either a daring adventure or nothing at all.', 'author' => 'Helen Keller', 'category' => 'Life'],
            ['text' => 'The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.', 'author' => 'Mark Twain', 'category' => 'Life'],
            ['text' => 'Don\'t cry because it\'s over, smile because it happened.', 'author' => 'Dr. Seuss', 'category' => 'Life'],
            ['text' => 'Life shrinks or expands in proportion to one\'s courage.', 'author' => 'Anaïs Nin', 'category' => 'Life'],
            ['text' => 'He who has a why to live for can bear almost any how.', 'author' => 'Friedrich Nietzsche', 'category' => 'Life'],
            ['text' => 'Every man dies. Not every man really lives.', 'author' => 'William Wallace (as portrayed in Braveheart)', 'category' => 'Life'],
            ['text' => 'Believe that life is worth living and your belief will help create the fact.', 'author' => 'William James', 'category' => 'Life'],
            ['text' => 'You have within you right now, everything you need to deal with whatever the world can throw at you.', 'author' => 'Brian Tracy', 'category' => 'Life'],
            ['text' => 'The tragedy of life is not that it ends so soon, but that we wait so long to begin it.', 'author' => 'W.M. Lewis', 'category' => 'Life'],
            ['text' => 'Life is not a problem to be solved, but a reality to be experienced.', 'author' => 'Søren Kierkegaard', 'category' => 'Life'],
            ['text' => 'It is not length of life, but depth of life.', 'author' => 'Ralph Waldo Emerson', 'category' => 'Life'],
            ['text' => 'And in the end, the love you take is equal to the love you make.', 'author' => 'Paul McCartney', 'category' => 'Life'],

            // Emotion
            ['text' => 'The emotion that can break your heart is sometimes the very one that heals it.', 'author' => 'Nicholas Sparks', 'category' => 'Emotion'],
            ['text' => 'Your intellect may be confused, but your emotions will never lie to you.', 'author' => 'Roger Ebert', 'category' => 'Emotion'],
            ['text' => 'Feelings are not supposed to be logical. Dangerous is the man who has rationalized his emotions.', 'author' => 'David Borenstein', 'category' => 'Emotion'],
            ['text' => 'The best and most beautiful things in the world cannot be seen or even touched. They must be felt with the heart.', 'author' => 'Helen Keller', 'category' => 'Emotion'],
            ['text' => 'Emotional intelligence is the ability to make emotions work for you, instead of against you.', 'author' => 'Daniel Goleman', 'category' => 'Emotion'],
            ['text' => 'Unexpressed emotions will never die. They are buried alive and will come forth later in uglier ways.', 'author' => 'Sigmund Freud', 'category' => 'Emotion'],
            ['text' => 'You cannot control what happens to you, but you can control your attitude toward it. It is our emotional response that creates the experience.', 'author' => 'Brian Tracy', 'category' => 'Emotion'],
            ['text' => 'The emotion of love is not an emotion at all; it is a promise, a decision, a commitment.', 'author' => 'M. Scott Peck', 'category' => 'Emotion'],
            ['text' => 'When dealing with people, remember you are not dealing with creatures of logic, but creatures of emotion.', 'author' => 'Dale Carnegie', 'category' => 'Emotion'],
            ['text' => 'Your pain is the breaking of the shell that encloses your understanding.', 'author' => 'Kahlil Gibran', 'category' => 'Emotion'],
            ['text' => 'I don\'t want to be at the mercy of my emotions. I want to use them, to enjoy them, and to dominate them.', 'author' => 'Oscar Wilde', 'category' => 'Emotion'],
            ['text' => 'Between stimulus and response there is a space. In that space is our power to choose our response. In our response lies our growth and our freedom.', 'author' => 'Viktor Frankl', 'category' => 'Emotion'],
            ['text' => 'The only way out is through.', 'author' => 'Robert Frost', 'category' => 'Emotion'],
            ['text' => 'Emotions are like waves. You cannot stop them from coming, but you can choose which ones to surf.', 'author' => 'Jonatan Mårtensson', 'category' => 'Emotion'],
            ['text' => 'We cannot selectively numb emotions. When we numb the painful emotions, we also numb the positive emotions.', 'author' => 'Brené Brown', 'category' => 'Emotion'],
            ['text' => 'Crying does not indicate that you are weak. Since birth, it has always been a sign that you are alive.', 'author' => 'Charlotte Brontë', 'category' => 'Emotion'],
            ['text' => 'There can be no transforming of darkness into light and of apathy into movement without emotion.', 'author' => 'Carl Jung', 'category' => 'Emotion'],
            ['text' => 'Let everything happen to you: beauty and terror. Just keep going. No feeling is final.', 'author' => 'Rainer Maria Rilke', 'category' => 'Emotion'],
            ['text' => 'The sign of an intelligent people is their ability to control their emotions by the application of reason.', 'author' => 'Marya Mannes', 'category' => 'Emotion'],
            ['text' => 'One thing you can\'t hide—is when you\'re crippled inside.', 'author' => 'John Lennon', 'category' => 'Emotion'],
            ['text' => 'Emotion is the chief source of all becoming-conscious. There can be no transforming of darkness into light without emotion.', 'author' => 'Carl Jung', 'category' => 'Emotion'],
            ['text' => 'Feel what you need to feel. Then let it go. Do not let it define you.', 'author' => 'J. R. Ward', 'category' => 'Emotion'],
            ['text' => 'The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.', 'author' => 'Victor Hugo', 'category' => 'Emotion'],
            ['text' => 'Don\'t let your emotions overpower your intelligence.', 'author' => 'Drake', 'category' => 'Emotion'],
            ['text' => 'There is no greater sorrow than to recall happiness in times of misery.', 'author' => 'Dante Alighieri', 'category' => 'Emotion'],
            ['text' => 'Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.', 'author' => 'Mark Twain', 'category' => 'Emotion'],
            ['text' => 'The walls we build around us to keep sadness out also keeps out the joy.', 'author' => 'Jim Rohn', 'category' => 'Emotion'],
            ['text' => 'What worries you masters you.', 'author' => 'John Locke', 'category' => 'Emotion'],
            ['text' => 'Life is a train of moods like a string of beads; and as we pass through them they prove to be many-colored lenses which paint the world their own hue.', 'author' => 'Ralph Waldo Emerson', 'category' => 'Emotion'],
            ['text' => 'To feel intensely is not a symptom of weakness; it is the trademark of the truly alive and compassionate.', 'author' => 'Anthon St. Maarten', 'category' => 'Emotion'],

            // Being Heard
            ['text' => 'The most basic of all human needs is the need to understand and be understood. The best way to understand people is to listen to them.', 'author' => 'Ralph G. Nichols', 'category' => 'Being Heard'],
            ['text' => 'Being heard is so close to being loved that for the average person, they are almost indistinguishable.', 'author' => 'David W. Augsburger', 'category' => 'Being Heard'],
            ['text' => 'The greatest compliment that was ever paid me was when one asked me what I thought, and attended to my answer.', 'author' => 'Henry David Thoreau', 'category' => 'Being Heard'],
            ['text' => 'Speak only if it improves upon the silence.', 'author' => 'Mahatma Gandhi', 'category' => 'Being Heard'],
            ['text' => 'There is a difference between listening and waiting for your turn to speak.', 'author' => 'Simon Sinek', 'category' => 'Being Heard'],
            ['text' => 'Raise your words, not your voice. It is rain that grows flowers, not thunder.', 'author' => 'Rumi', 'category' => 'Being Heard'],
            ['text' => 'To say nothing, especially when speaking, is half the art of diplomacy.', 'author' => 'Will Durant', 'category' => 'Being Heard'],
            ['text' => 'One of the deepest secrets of life is that all that is really worth doing is what we do for others. But to do that, we must first be heard.', 'author' => 'Lewis Carroll (paraphrased sentiment)', 'category' => 'Being Heard'],
            ['text' => 'The right to be heard does not automatically include the right to be taken seriously.', 'author' => 'Hubert H. Humphrey', 'category' => 'Being Heard'],
            ['text' => 'You don\'t get a second chance to make a first impression, but you get a thousand chances to make someone feel heard.', 'author' => 'Anonymous', 'category' => 'Being Heard'],
            ['text' => 'When people talk, listen completely. Most people never listen.', 'author' => 'Ernest Hemingway', 'category' => 'Being Heard'],
            ['text' => 'Your voice is your identity. If you don\'t use it, you\'re halfway to being invisible.', 'author' => 'Chimamanda Ngozi Adichie', 'category' => 'Being Heard'],
            ['text' => 'Listening is not merely not talking, though even that is beyond most of our powers; it means taking a vigorous, human interest in what is being told us.', 'author' => 'Alice Duer Miller', 'category' => 'Being Heard'],
            ['text' => 'The quieter you become, the more you are able to hear.', 'author' => 'Ram Dass', 'category' => 'Being Heard'],
            ['text' => 'Storytelling is a way of being heard. You can scream at the top of your lungs, but if you tell a story, people lean in.', 'author' => 'Dave Grohl', 'category' => 'Being Heard'],
            ['text' => 'I speak not for myself but for those without voice... those who have fought for their rights... their right to live in peace, their right to be heard.', 'author' => 'Malala Yousafzai', 'category' => 'Being Heard'],
            ['text' => 'We have two ears and one mouth so that we can listen twice as much as we speak.', 'author' => 'Epictetus', 'category' => 'Being Heard'],
            ['text' => 'The deepest principle in human nature is the craving to be appreciated. And at the root of appreciation is the feeling of being heard.', 'author' => 'William James', 'category' => 'Being Heard'],
            ['text' => 'If you want to be listened to, you should put in the time listening.', 'author' => 'Marge Piercy', 'category' => 'Being Heard'],
            ['text' => 'Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.', 'author' => 'Winston Churchill', 'category' => 'Being Heard'],
            ['text' => 'Attention is the rarest and purest form of generosity.', 'author' => 'Simone Weil', 'category' => 'Being Heard'],
            ['text' => 'To be heard, you must first be willing to hear.', 'author' => 'Stephen R. Covey', 'category' => 'Being Heard'],
            ['text' => 'The greatest tragedy in the world is not the oppression of the unheard; it is the silence of those who have a voice but choose not to use it.', 'author' => 'Martin Luther King Jr.', 'category' => 'Being Heard'],
            ['text' => 'Listening is an art that requires attention over talent, spirit over ego, others over self.', 'author' => 'Dean Jackson', 'category' => 'Being Heard'],
            ['text' => 'We need people who can listen without judgment and hear without prejudice.', 'author' => 'Bryant McGill', 'category' => 'Being Heard'],
            ['text' => 'The only way to be heard in a world full of noise is to whisper something true.', 'author' => 'Pico Iyer', 'category' => 'Being Heard'],
            ['text' => 'Being heard doesn\'t mean being agreed with; it means being acknowledged.', 'author' => 'Oprah Winfrey', 'category' => 'Being Heard'],
            ['text' => 'If speaking is silver, then listening is gold.', 'author' => 'Turkish Proverb', 'category' => 'Being Heard'],
            ['text' => 'An appreciative listener is always stimulating.', 'author' => 'Agatha Christie', 'category' => 'Being Heard'],
            ['text' => 'Your silence will not protect you. But your voice might save someone else.', 'author' => 'Audre Lorde', 'category' => 'Being Heard'],

            // Letting Go
            ['text' => 'Letting go doesn\'t mean that you don\'t care about someone anymore. It\'s just realizing that the only person you really have control over is yourself.', 'author' => 'Deborah Reber', 'category' => 'Letting Go'],
            ['text' => 'Some of us think holding on makes us strong, but sometimes it is letting go.', 'author' => 'Hermann Hesse', 'category' => 'Letting Go'],
            ['text' => 'The truth is, unless you let go, unless you forgive yourself, unless you forgive the situation, unless you realize that the situation is over, you cannot move forward.', 'author' => 'Steve Maraboli', 'category' => 'Letting Go'],
            ['text' => 'Let go or be dragged.', 'author' => 'Zen Proverb', 'category' => 'Letting Go'],
            ['text' => 'In the process of letting go, you will lose many things from the past, but you will find yourself.', 'author' => 'Deepak Chopra', 'category' => 'Letting Go'],
            ['text' => 'When I let go of what I am, I become what I might be.', 'author' => 'Lao Tzu', 'category' => 'Letting Go'],
            ['text' => 'The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'author' => 'Alan Watts', 'category' => 'Letting Go'],
            ['text' => 'Holding onto anger is like drinking poison and expecting the other person to die.', 'author' => 'Buddha', 'category' => 'Letting Go'],
            ['text' => 'Sometimes the hardest part isn\'t letting go but rather learning to start over.', 'author' => 'Nicole Sobon', 'category' => 'Letting Go'],
            ['text' => 'Letting go means to come to the realization that some people are a part of your history, but not a part of your destiny.', 'author' => 'Steve Maraboli', 'category' => 'Letting Go'],
            ['text' => 'You can only lose what you cling to.', 'author' => 'Buddha', 'category' => 'Letting Go'],
            ['text' => 'If you want to fly in the sky, you need to leave the earth. If you want to move forward, you need to let go of the past that drags you down.', 'author' => 'Amit Ray', 'category' => 'Letting Go'],
            ['text' => 'Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.', 'author' => 'Oprah Winfrey', 'category' => 'Letting Go'],
            ['text' => 'There is a time for departure even when there\'s no certain place to go.', 'author' => 'Tennessee Williams', 'category' => 'Letting Go'],
            ['text' => 'Letting go is the willingness to change your beliefs in order to bring more peace and joy into your life instead of holding onto beliefs that bring pain and suffering.', 'author' => 'Hal Tipper', 'category' => 'Letting Go'],
            ['text' => 'Sometimes letting things go is an act of far greater power than defending or hanging on.', 'author' => 'Eckhart Tolle', 'category' => 'Letting Go'],
            ['text' => 'To let go is to release the images and emotions, the grudges and fears, the clingings and disappointments of the past that bind our spirit.', 'author' => 'Jack Kornfield', 'category' => 'Letting Go'],
            ['text' => 'The art of letting go is simply a deeply focused choice to release the weight of what no longer belongs to you.', 'author' => 'Morgan Harper Nichols', 'category' => 'Letting Go'],
            ['text' => 'Even though you may want to move forward in your life, you may have one foot on the brakes. In order to be free, we must learn how to let go.', 'author' => 'Mary Manin Morrissey', 'category' => 'Letting Go'],
            ['text' => 'Nothing in the universe can stop you from letting go and starting over.', 'author' => 'Guy Finley', 'category' => 'Letting Go'],
            ['text' => 'The beautiful journey of today can only begin when we learn to let go of yesterday.', 'author' => 'Steve Maraboli', 'category' => 'Letting Go'],
            ['text' => 'People have a hard time letting go of their suffering. Out of a fear of the unknown, they prefer suffering that is familiar.', 'author' => 'Thich Nhat Hanh', 'category' => 'Letting Go'],
            ['text' => 'One of the happiest moments in life is when you find the courage to let go of what you can\'t change.', 'author' => 'Robert Tew', 'category' => 'Letting Go'],
            ['text' => 'Let go of the idea that the path you\'re on right now is the only path. The universe has a map far larger than your own.', 'author' => 'Melody Beattie', 'category' => 'Letting Go'],
            ['text' => 'The day I understood everything, was the day I stopped trying to figure everything out. The day I knew peace was the day I let everything go.', 'author' => 'C. JoyBell C.', 'category' => 'Letting Go'],
            ['text' => 'Accept yourself, love yourself, and keep moving forward. If you want to fly, you have to give up what weighs you down.', 'author' => 'Roy T. Bennett', 'category' => 'Letting Go'],
            ['text' => 'To let go does not mean to get rid of. To let go means to allow things to be as they are, without clinging.', 'author' => 'Jon Kabat-Zinn', 'category' => 'Letting Go'],
            ['text' => 'Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future happiness.', 'author' => 'Steve Maraboli', 'category' => 'Letting Go'],
            ['text' => 'You will find that it is necessary to let things go; simply for the reason that they are heavy.', 'author' => 'C. JoyBell C.', 'category' => 'Letting Go'],
            ['text' => 'Let go. Why do you cling to pain? There is nothing you can do about the wrongs of yesterday. It is not yours to judge. Why hold on to the very thing which keeps you from hope and love?', 'author' => 'Leo Buscaglia', 'category' => 'Letting Go'],

            // Hidden Feelings
            ['text' => 'The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too.', 'author' => 'Ernest Hemingway', 'category' => 'Hidden Feelings'],
            ['text' => 'I am a forest, and a night of dark trees: but he who is not afraid of my darkness, will find banks full of roses under my cypresses.', 'author' => 'Friedrich Nietzsche', 'category' => 'Hidden Feelings'],
            ['text' => 'We are all like the bright moon, we still have our darker side.', 'author' => 'Kahlil Gibran', 'category' => 'Hidden Feelings'],
            ['text' => 'I hide my feelings so well, I\'ve convinced myself that they don\'t exist.', 'author' => 'Unknown', 'category' => 'Hidden Feelings'],
            ['text' => 'The human heart has hidden treasures, in secret kept, in silence sealed.', 'author' => 'Charlotte Brontë', 'category' => 'Hidden Feelings'],
            ['text' => 'There is a sacredness in tears. They are not the mark of weakness, but of power. They speak more eloquently than ten thousand tongues.', 'author' => 'Washington Irving', 'category' => 'Hidden Feelings'],
            ['text' => 'It\'s amazing how someone can break your heart and you can still love them with all the little pieces.', 'author' => 'Ella Harper', 'category' => 'Hidden Feelings'],
            ['text' => 'I\'m not upset that you lied to me. I\'m upset that from now on I can\'t believe you.', 'author' => 'Friedrich Nietzsche', 'category' => 'Hidden Feelings'],
            ['text' => 'The worst feeling is not being lonely. It\'s being forgotten by someone you can\'t forget.', 'author' => 'Haruki Murakami', 'category' => 'Hidden Feelings'],
            ['text' => 'Beneath my poised exterior, there\'s a world of unspoken words and hidden tears.', 'author' => 'Nikki Rowe', 'category' => 'Hidden Feelings'],
            ['text' => 'I think perhaps I will always be the one who loves more. I\'ll never have the upper hand, the indifference.', 'author' => 'Sylvia Plath', 'category' => 'Hidden Feelings'],
            ['text' => 'Sometimes the person who tries to keep everyone else happy is the loneliest person in the room.', 'author' => 'Bridgett Devoue', 'category' => 'Hidden Feelings'],
            ['text' => 'The walls we build around us to keep out the sadness also keep out the joy.', 'author' => 'Jim Rohn', 'category' => 'Hidden Feelings'],
            ['text' => 'I am learning to love the sound of my feet walking away from things not meant for me.', 'author' => 'A.G.', 'category' => 'Hidden Feelings'],
            ['text' => 'You don\'t have to tell everyone you\'re hurting. Just because it\'s invisible doesn\'t mean it isn\'t real.', 'author' => 'Unknown', 'category' => 'Hidden Feelings'],
            ['text' => 'There is a loneliness more precious than life. There is a freedom more precious than the world. Infinitely more precious than life and the world is that moment when one is alone with one\'s hidden feelings.', 'author' => 'Anna de Noailles', 'category' => 'Hidden Feelings'],
            ['text' => 'I have a million things to talk to you about. All I can manage to say is nothing.', 'author' => 'John Green', 'category' => 'Hidden Feelings'],
            ['text' => 'A quiet heart is content with what it does not understand, but a hidden heart aches with what it cannot express.', 'author' => 'Yasmin Mogahed', 'category' => 'Hidden Feelings'],
            ['text' => 'The strongest people are not those who show strength in front of us but those who win battles we know nothing about.', 'author' => 'Jonathan Harnisch', 'category' => 'Hidden Feelings'],
            ['text' => 'What is concealed inside you, will appear on the outside. What you hide in your heart, will be revealed on your face.', 'author' => 'Rumi', 'category' => 'Hidden Feelings'],
            ['text' => 'I feel things so deeply that I often have to pretend I feel nothing at all.', 'author' => 'Sue Zhao', 'category' => 'Hidden Feelings'],
            ['text' => 'Sometimes the most beautiful things are the most broken things. That is where the light gets in.', 'author' => 'Ernest Hemingway', 'category' => 'Hidden Feelings'],
            ['text' => 'The emotion that you suppress today will find a way to express itself tomorrow.', 'author' => 'Sigmund Freud', 'category' => 'Hidden Feelings'],
            ['text' => 'People think that intimacy is about sex. But intimacy is about truth. When you realize you can tell someone your truth, when you can show yourself to them, when you stand in front of them and their response is \'you\'re safe with me\'—that\'s intimacy.', 'author' => 'Taylor Jenkins Reid', 'category' => 'Hidden Feelings'],
            ['text' => 'He wore his pain like a secret, tucked deep beneath his ribs where no one would think to look.', 'author' => 'Atticus Poetry', 'category' => 'Hidden Feelings'],
            ['text' => 'The loudest hearts are often the quietest rooms.', 'author' => 'C. Churchill', 'category' => 'Hidden Feelings'],
            ['text' => 'You can close your eyes to the things you don\'t want to see, but you can\'t close your heart to the things you don\'t want to feel.', 'author' => 'Johnny Depp', 'category' => 'Hidden Feelings'],
            ['text' => 'I\'m a collection of dismantled almosts.', 'author' => 'Anne Sexton', 'category' => 'Hidden Feelings'],
            ['text' => 'It\'s hard to reveal your inner world, because when you do, you\'re not just showing people your garden—you\'re giving them a map to your graves.', 'author' => 'Iain Thomas', 'category' => 'Hidden Feelings'],
            ['text' => 'And then I realized that to be alone with your feelings is the only way to truly understand them. The world is loud, but your hidden feelings are the quietest, truest thing about you.', 'author' => 'Bianca Sparacino', 'category' => 'Hidden Feelings'],

            // Unspoken Words
            ['text' => 'The bitterest tears shed over graves are for words left unsaid and deeds left undone.', 'author' => 'Harriet Beecher Stowe', 'category' => 'Unspoken Words'],
            ['text' => 'Unspoken words between two people are like a wall slowly built of invisible bricks.', 'author' => 'Unknown', 'category' => 'Unspoken Words'],
            ['text' => 'The most important things are the hardest to say.', 'author' => 'Stephen King', 'category' => 'Unspoken Words'],
            ['text' => 'Sometimes the words we leave unspoken are the most important ones that should have been said.', 'author' => 'Meredith Grey (Grey\'s Anatomy)', 'category' => 'Unspoken Words'],
            ['text' => 'Silence is the most powerful scream.', 'author' => 'Anonymous', 'category' => 'Unspoken Words'],
            ['text' => 'We are masters of the unsaid words, but slaves of those we let slip out.', 'author' => 'Winston Churchill', 'category' => 'Unspoken Words'],
            ['text' => 'I have learned now that while those who speak about one\'s miseries usually hurt, those who keep silence hurt more.', 'author' => 'C.S. Lewis', 'category' => 'Unspoken Words'],
            ['text' => 'There are things known and there are things unknown, and in between are the doors of perception.', 'author' => 'Aldous Huxley', 'category' => 'Unspoken Words'],
            ['text' => 'The words you never spoke are louder than any noise you could have made.', 'author' => 'R.M. Drake', 'category' => 'Unspoken Words'],
            ['text' => 'What is left unsaid, remains unforgotten.', 'author' => 'Cassandra Clare', 'category' => 'Unspoken Words'],
            ['text' => 'Sometimes the most healing thing we can do is give voice to the silence we\'ve carried for too long.', 'author' => 'Brené Brown', 'category' => 'Unspoken Words'],
            ['text' => 'I am jealous of the words that rest on your tongue but never reach my ears.', 'author' => 'Christopher Poindexter', 'category' => 'Unspoken Words'],
            ['text' => 'The space between what you want to say and what you actually say is where the soul lives.', 'author' => 'Ocean Vuong', 'category' => 'Unspoken Words'],
            ['text' => 'Unspoken words are the most painful kind of goodbye.', 'author' => 'Unknown', 'category' => 'Unspoken Words'],
            ['text' => 'There is a voice that doesn\'t use words. Listen.', 'author' => 'Rumi', 'category' => 'Unspoken Words'],
            ['text' => 'I always had the words but never the courage. So they stayed inside me, building a home I could never leave.', 'author' => 'Sarah Kay', 'category' => 'Unspoken Words'],
            ['text' => 'The heaviest burdens in life are the thoughts we carry and never express.', 'author' => 'Ralph Waldo Emerson', 'category' => 'Unspoken Words'],
            ['text' => 'Words unsaid are like arrows stuck in the throat. They poison the blood and silence the soul.', 'author' => 'Unknown', 'category' => 'Unspoken Words'],
            ['text' => 'We swallow the words we most want to say, and choke on them in the dark.', 'author' => 'Atticus Poetry', 'category' => 'Unspoken Words'],
            ['text' => 'I write because I don\'t know what I think until I read what I say.', 'author' => 'Flannery O\'Connor', 'category' => 'Unspoken Words'],
            ['text' => 'The silence between two people who once had everything to say is the loudest sound in the world.', 'author' => 'Beau Taplin', 'category' => 'Unspoken Words'],
            ['text' => 'Sometimes not speaking says more than all the words in the world.', 'author' => 'Colleen Hoover', 'category' => 'Unspoken Words'],
            ['text' => 'All the words I never said are written in the spaces between the lines of my life.', 'author' => 'Unknown', 'category' => 'Unspoken Words'],
            ['text' => 'A closed mouth gathers no foot, but it also gathers no connection.', 'author' => 'Mark Twain (adapted)', 'category' => 'Unspoken Words'],
            ['text' => 'The greatest distance between two people is not misunderstanding. It is the words one was too afraid to say.', 'author' => 'S.Z.', 'category' => 'Unspoken Words'],
            ['text' => 'My tongue will tell the anger of my heart, or else my heart concealing it will break.', 'author' => 'William Shakespeare', 'category' => 'Unspoken Words'],
            ['text' => 'Unspoken expectations are premeditated resentments.', 'author' => 'Neil Strauss', 'category' => 'Unspoken Words'],
            ['text' => 'Some silences are answers. Some unspoken words are confessions.', 'author' => 'Unknown', 'category' => 'Unspoken Words'],
            ['text' => 'The cruelest thing you can do to another person is to take away their words. To make them feel that their voice does not matter. To let the unspoken pile up until they drown in it.', 'author' => 'Margaret Atwood (paraphrased sentiment)', 'category' => 'Unspoken Words'],
            ['text' => 'In the end, we will remember not the words of our enemies, but the silence of our friends.', 'author' => 'Martin Luther King Jr.', 'category' => 'Unspoken Words'],

            // Healing
            ['text' => 'Healing begins where the wound was made.', 'author' => 'Alice Walker', 'category' => 'Healing'],
            ['text' => 'The wound is the place where the Light enters you.', 'author' => 'Rumi', 'category' => 'Healing'],
            ['text' => 'Healing yourself is connected with healing others.', 'author' => 'Yoko Ono', 'category' => 'Healing'],
            ['text' => 'Although the world is full of suffering, it is also full of the overcoming of it.', 'author' => 'Helen Keller', 'category' => 'Healing'],
            ['text' => 'Our sorrows and wounds are healed only when we touch them with compassion.', 'author' => 'Buddha', 'category' => 'Healing'],
            ['text' => 'The soul always knows what to do to heal itself. The challenge is to silence the mind.', 'author' => 'Caroline Myss', 'category' => 'Healing'],
            ['text' => 'Healing takes time, and asking for help is a courageous step.', 'author' => 'Mariska Hargitay', 'category' => 'Healing'],
            ['text' => 'To heal is to touch with love that which we previously touched with fear.', 'author' => 'Stephen Levine', 'category' => 'Healing'],
            ['text' => 'You have been criticizing yourself for years and it hasn\'t worked. Try approving of yourself and see what happens.', 'author' => 'Louise Hay', 'category' => 'Healing'],
            ['text' => 'Sometimes you have to kind of die inside in order to rise from your own ashes and believe in yourself and love yourself to become a new person.', 'author' => 'Gerard Way', 'category' => 'Healing'],
            ['text' => 'The greatest healing therapy is friendship and love.', 'author' => 'Hubert H. Humphrey', 'category' => 'Healing'],
            ['text' => 'Healing doesn\'t mean the damage never existed. It means the damage no longer controls our lives.', 'author' => 'Akshay Dubey', 'category' => 'Healing'],
            ['text' => 'Just like there\'s always time for pain, there\'s always time for healing.', 'author' => 'Jennifer Brown', 'category' => 'Healing'],
            ['text' => 'Part of the healing process is sharing with other people who care.', 'author' => 'Jerry Cantrell', 'category' => 'Healing'],
            ['text' => 'What happens when people open their hearts? They get better.', 'author' => 'Haruki Murakami', 'category' => 'Healing'],
            ['text' => 'Healing requires from us to stop struggling, but to enjoy life more and endure it less.', 'author' => 'Darina Stoyanova', 'category' => 'Healing'],
            ['text' => 'Emotional pain cannot kill you, but running from it can. Allow. Embrace. Let yourself feel. Let yourself heal.', 'author' => 'Vironika Tugaleva', 'category' => 'Healing'],
            ['text' => 'The practice of forgiveness is our most important contribution to the healing of the world.', 'author' => 'Marianne Williamson', 'category' => 'Healing'],
            ['text' => 'I have come to believe that caring for myself is not self-indulgent. Caring for myself is an act of survival.', 'author' => 'Audre Lorde', 'category' => 'Healing'],
            ['text' => 'Every step taken in mindfulness brings us one step closer to healing ourselves and the planet.', 'author' => 'Thich Nhat Hanh', 'category' => 'Healing'],
            ['text' => 'The dark does not destroy the light; it defines it. It\'s our fear of the dark that casts our joy into the shadows.', 'author' => 'Brené Brown', 'category' => 'Healing'],
            ['text' => 'We are all broken, that\'s how the light gets in.', 'author' => 'Ernest Hemingway', 'category' => 'Healing'],
            ['text' => 'Healing is an art. It takes time, it takes practice, it takes love.', 'author' => 'Maza Dohta', 'category' => 'Healing'],
            ['text' => 'You don\'t have to be positive all the time. It\'s perfectly okay to feel sad, angry, annoyed, frustrated, scared, or anxious. Having feelings doesn\'t make you a negative person. It makes you human.', 'author' => 'Lori Deschene', 'category' => 'Healing'],
            ['text' => 'Your body hears everything your mind says. Stay kind. Stay compassionate. Healing begins with the conversation inside you.', 'author' => 'Naomi Judd', 'category' => 'Healing'],
            ['text' => 'As soon as healing takes place, go out and heal somebody else.', 'author' => 'Maya Angelou', 'category' => 'Healing'],
            ['text' => 'The only way out is through.', 'author' => 'Robert Frost', 'category' => 'Healing'],
            ['text' => 'We think our job as humans is to avoid pain. Our job as parents is to protect our children from pain. But the truth is, our job is to navigate it. To survive it. To let it carve us into something deeper and more compassionate.', 'author' => 'Glennon Doyle', 'category' => 'Healing'],
            ['text' => 'Owning our story and loving ourselves through that process is the bravest thing that we\'ll ever do.', 'author' => 'Brené Brown', 'category' => 'Healing'],
            ['text' => 'Ring the bells that still can ring. Forget your perfect offering. There is a crack, a crack in everything. That\'s how the light gets in.', 'author' => 'Leonard Cohen', 'category' => 'Healing'],
        ];

        foreach ($quotes as $quote) {
            Quote::firstOrCreate($quote);
        }
    }
}
